In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/HP/Downloads/heart (2).csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [4]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [8]:
from sklearn import preprocessing
processing=preprocessing.MinMaxScaler()
x_train=processing.fit_transform(x_train)
x_test=processing.fit_transform(x_test)
print(x_test)

[[0.64583333 1.         0.         ... 1.         0.5        1.        ]
 [0.45833333 0.         0.66666667 ... 1.         0.         0.66666667]
 [0.27083333 1.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.72916667 0.         0.66666667 ... 1.         0.         1.        ]
 [0.27083333 1.         0.         ... 1.         0.         0.66666667]
 [0.45833333 1.         0.66666667 ... 1.         0.25       1.        ]]


In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=7)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(y_pred)

[0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1
 0 0 1 1 0 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1
 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 1 0 1 1 1 0
 1 0 1 1 1 0 1 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0
 0 0 1 1 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 0 1 1 0 0
 0 1 1 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 1 1 1 1 0 0 1
 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0
 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 0 1 1 0 1 0 1 0 1 0 0 0
 0 1 1 0 1 1 1 1 0 1 1 1]


In [10]:
print(classifier.predict([[52,1,0,125,212,0,1,168,0,1.0,2,2,3]]))

[0]


In [11]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=classification_report(y_test,y_pred)
result1=confusion_matrix(y_test,y_pred)
result2=accuracy_score(y_test,y_pred)
print(result)
print(result1)
print(result2)

              precision    recall  f1-score   support

           0       0.91      0.79      0.85       161
           1       0.80      0.92      0.85       147

    accuracy                           0.85       308
   macro avg       0.86      0.85      0.85       308
weighted avg       0.86      0.85      0.85       308

[[127  34]
 [ 12 135]]
0.8506493506493507
